#!/bin/bash
set -e


PKG_DIR=libpcap

#===name=libpcap
mkdir -p $SRC_DIR/$PKG_DIR
cd $SRC_DIR/$PKG_DIR
#===version=libpcap-1.4.0.tar.gz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PKG_DIR/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PKG_DIR/$PACKAGE $PACKAGE
  elif [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 ${FTP_SERVER}svn/l/$PACKAGE || \
    wget -T 30 -t 5 http://www.tcpdump.org/release/libpcap-1.4.0.tar.gz
    cp $PACKAGE $SRC_ARCHIVE
  fi
fi
echo "56e88a5aabdd1e04414985ac24f7e76c  $PACKAGE" | md5sum -c -


if [ "${PACKAGE%.zip}" = "${PACKAGE}" ]; then
 if [[ -e unpacked ]] ; then
  UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^./@@;s@/.*@@'`
  [[ -n $UNPACKDIR ]] && [[ -d $UNPACKDIR ]] && #=== CLEANUP2 rm -rf $UNPACKDIR
 fi
 tar -xvf $PACKAGE > unpacked
 UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^./@@;s@/.*@@'`
else
 UNPACKDIR=${PACKAGE%.zip}
 [[ -n $UNPACKDIR ]] && [[ -d $UNPACKDIR ]] && #=== CLEANUP3 rm -rf $UNPACKDIR
 unzip -d $UNPACKDIR ${PACKAGE}
fi
#========== UNPACKDIR cd $UNPACKDIR
./configure --prefix=/usr &&
make
make -j1 install
#===== LDCONFIG1ldconfig

cd $SRC_DIR/$PKG_DIR
#===CLEANUP1 rm -rf $UNPACKDIR unpacked

exit