#!/bin/bash
set -e


PKG_DIR=libgcrypt

#===name=libgcrypt
mkdir -p $SRC_DIR/$PKG_DIR
cd $SRC_DIR/$PKG_DIR
#===version=libgcrypt-1.5.3.tar.bz2
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PKG_DIR/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PKG_DIR/$PACKAGE $PACKAGE
  elif [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 ${FTP_SERVER}svn/l/$PACKAGE || \
    wget -T 30 -t 5 ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.5.3.tar.bz2
    cp $PACKAGE $SRC_ARCHIVE
  fi
fi
echo "993159b2924ae7b0e4eaff0743c2db35  $PACKAGE" | md5sum -c -


if [ "${PACKAGE%.zip}" = "${PACKAGE}" ]; then
 if [[ -e unpacked ]] ; then
  UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^./@@;s@/.*@@'`
  [[ -n $UNPACKDIR ]] && [[ -d $UNPACKDIR ]] && #=== CLEANUP2 rm -rf $UNPACKDIR
 fi
 tar -xvf $PACKAGE > unpacked
 UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^./@@;s@/.*@@'`
else
 UNPACKDIR=${PACKAGE%.zip}
 [[ -n $UNPACKDIR ]] && [[ -d $UNPACKDIR ]] && #=== CLEANUP3 rm -rf $UNPACKDIR
 unzip -d $UNPACKDIR ${PACKAGE}
fi
#========== UNPACKDIR cd $UNPACKDIR
./configure --prefix=/usr --disable-static &&
make
make -C doc pdf ps html &&
makeinfo --html --no-split -o doc/gcrypt_nochunks.html doc/gcrypt.texi &&
makeinfo --plaintext       -o doc/gcrypt.txt           doc/gcrypt.texi
#make -k check || true
make -j1 install &&
install -v -dm755   /usr/share/doc/libgcrypt-1.5.3 &&
install -v -m644    README doc/{README.apichanges,fips*,libgcrypt*} \
                    /usr/share/doc/libgcrypt-1.5.3
install -v -dm755   /usr/share/doc/libgcrypt-1.5.3/html &&
install -v -m644 doc/gcrypt.html/* \
                    /usr/share/doc/libgcrypt-1.5.3/html &&
install -v -m644 doc/gcrypt_nochunks.html \
                    /usr/share/doc/libgcrypt-1.5.3 &&
install -v -m644 doc/gcrypt.{pdf,ps,dvi,txt,texi} \
                    /usr/share/doc/libgcrypt-1.5.3
#===== LDCONFIG1ldconfig

cd $SRC_DIR/$PKG_DIR
#===CLEANUP1 rm -rf $UNPACKDIR unpacked

exit