#!/bin/sh

set -e

if [ ! -d /etc/xml ]; then
	install -m 0755 -d /etc/xml
fi

if [ ! -f /etc/xml/catalog ]; then
	xmlcatalog --noout --create /etc/xml/catalog
fi

xmlcatalog --noout --add "rewriteSystem" \
	"http://docbook.sourceforge.net/release/xsl/1.77.1" \
	"/usr/share/xml/docbook/xsl-stylesheets-1.77.1" \
	/etc/xml/catalog

xmlcatalog --noout --add "rewriteURI" \
	"http://docbook.sourceforge.net/release/xsl/1.77.1" \
	"/usr/share/xml/docbook/xsl-stylesheets-1.77.1" \
	/etc/xml/catalog

xmlcatalog --noout --add "rewriteSystem" \
	"http://docbook.sourceforge.net/release/xsl/current" \
	"/usr/share/xml/docbook/xsl-stylesheets-1.77.1" \
	/etc/xml/catalog

xmlcatalog --noout --add "rewriteURI" \
	"http://docbook.sourceforge.net/release/xsl/current" \
	"/usr/share/xml/docbook/xsl-stylesheets-1.77.1" \
	/etc/xml/catalog
